export const PRODUCTS = {
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_REQUESTED: "GET_PRODUCTS_REQUESTED",
  GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
  GET_FAV_PRODUCT: "GET_FAV_PRODUCT",
  GET_BASKET_PRODUCT: "GET_BASKET_PRODUCT",
};
