export const PRODUCTS = {
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_REQUESTED: "GET_PRODUCTS_REQUESTED",
  GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
  GET_FAV_PRODUCT: "GET_FAV_PRODUCT",
  GET_BASKET_PRODUCT: "GET_BASKET_PRODUCT",
};
export const MODAL = {
  SET_MODAL: "SET_MODAL",
  MODAL_CLOSE: "MODAL_CLOSE",
  SET_REMOVE_MODAL: "SET_REMOVE_MODAL",
  BUY_MODAL: "BUY_MODAL",
};
